yugregion/mayak_news/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import Rss


urlpatterns = patterns('yugregion.mayak_news.views',
    url(r'^$', 'news_index', name='mayak_news_list'),
    url(r'^page_(?P<page>\d+)/$', 'news_index', name='mayak_news_list_page'),
    url(r'^date_(?P<date>[0-9]{4}/[0-9]{2}/[0-9]{2})/$', 'news_date', name='mayak_news_date_list'),
    url(r'^date/json/$', 'news_date_json', name='mayak_news_date_json'),
    url(r'^(?P<news_id>\d+)/$', 'news_show', name='mayak_news_show'),
    url(r'^(?P<news_id>\d+)/more/$', 'day_news_more', name='mayak_day_news_more'),
    url(r'^rss/$', Rss()),
)

yugregion/mayak_video/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('yugregion.mayak_video.views',
    url(r'^$', 'program_video_archive', name='mayak_nucleum_program_video_archive_archive_last'),
    url(r'^(?P<pk>\d+)$', 'program_video_archive', name='mayak_nucleum_program_video_archive_archive'),
    url(r'^last/$', 'program_video_archive', name='mayak_nucleum_program_video_archive_archive_last'),
)

yugregion/shanson_news/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('yugregion.shanson_news.views',
    url(r'^$', 'news_index', name='shanson_news_list'),
    url(r'^page_(?P<page>\d+)/$', 'news_index', name='shanson_news_list_page'),
    url(r'^(?P<news_id>\d+)/$', 'news_show', name='shanson_news_show'),
    url(r'^(?P<news_id>\d+)/more/$', 'day_news_more', name='shanson_day_news_more'),
)

yugregion/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from planb.core.urls import urlpatterns

local_urlpatterns = patterns('',
    url(r'^mayak/', include('yugregion.mayak_nucleum.urls')),
    url(r'^shanson/', include('yugregion.shanson_nucleum.urls')),
)

urlpatterns = local_urlpatterns + urlpatterns

yugregion/mayak_nucleum/models.py
# -*- coding: utf-8 -*-

import datetime as dt
import pytils
import re

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField

from planb.core.models import PublishModel


class Hospes(PublishModel):
    name = models.CharField(max_length=255, verbose_name=u'Имя')
    surname = models.CharField(max_length=255, verbose_name=u'Фамилия')
    photo = models.ImageField(verbose_name=u'Фотография', upload_to=u'upload', null=True, blank=True, help_text=u'изображение обрезаеться до размеров 570x380')
    text = RichTextField(u'Текст', blank=True)
    transmission = models.ForeignKey('ProgramsArchive', verbose_name=u'Передача', null=True, blank=True)

    def __unicode__(self):
        return '%s %s' % (self.surname, self.name, )

    def name_surname(self):
        return '%s %s' % (self.name, self.surname, )

    def get_absolute_url(self):
        if self.transmission:
            return self.transmission.get_absolute_url()
        return reverse('mayak_index')

    class Meta:
        verbose_name = u'Гость'
        verbose_name_plural = u'Гости'
        ordering = ('transmission', 'surname', 'name')


DISPLAY_CHOISE = (
    ('main', u'Большое поле'),
    ('extra', u'Маленькое поле(внизу)'),
)


class Programs(PublishModel):
    title = models.CharField(max_length=255, verbose_name=u'Название')
    anons = RichTextField(u'Анонс', blank=True)
    description = RichTextField(u'Описание', blank=True)
    schedule = RichTextField(u'Расписание', blank=True)
    display = models.CharField(u'Способ отображения', max_length=21, choices=DISPLAY_CHOISE, default='main')
    weight = models.PositiveSmallIntegerField(u'Порядок',  default=0)
    staff = models.ManyToManyField('Staff', through="ProxyMayakStaffPrograms", blank=True, related_name='staff', )

    def __unicode__(self):
        return u'%s' % (self.title)

    class Meta:
        ordering = ('-display', 'weight', )
        verbose_name = u'Программа'
        verbose_name_plural = u'Программы'

    def get_archive_tree(self):
        b = self.programsarchive_set.all()
        a = dict()
        for y in b.dates('date', 'year'):
            m_l = list()
            for m in b.published(date__year=y.year).dates('date', 'month'):
                d_l = b.published(date__year=y.year, date__month=m.month).order_by('date')
                m_l.append([pytils.dt.ru_strftime(u'%B', date=m), d_l])
            m_l.reverse()
            a.update({y.year: m_l})
        return a

    def get_archive_for_year(self, year):
        return self.programsarchive_set.published(date__year=year)

    def get_photo(self):
        try: return ProgramsPhoto.objects.filter(program=self)[0]
        except: return None

    def get_photo_list(self):
        return ProgramsPhoto.objects.filter(program=self)

    def get_earliest_archive_date_for_datapicer(self):
        q = self.programsarchive_set.only('date').published().order_by('date')
        if q.count():
            earliest_date = q[0].date
            today = dt.date.today()
            alfa = earliest_date-today
            return '%dd' % alfa.days
        return None

    def get_latest_archive_date_for_datapicer(self):
        q = self.programsarchive_set.only('date').published()
        if q.count():
            latest_date = q.latest('date').date
            today = dt.date.today()
            alfa = latest_date-today
            return '%dd' % alfa.days
        return None


class ProgramsPhoto(PublishModel):
    program = models.ForeignKey(Programs, verbose_name=u'Программа')
    photo = models.ImageField(verbose_name=u'Фотография', upload_to=u'upload/programs', help_text=u'изображение обрезаеться до размеров 570x380')
    description = RichTextField(u'Описание', blank=True)
    weight = models.PositiveSmallIntegerField(u'Порядок', default=0)

    def __unicode__(self):
        return u'Фотография для %s' % (self.program)

    class Meta:
        ordering = ('weight', )
        verbose_name = u'Фотография программы'
        verbose_name_plural = u'Фотографии программы'


class ProgramsArchive(PublishModel):
    program = models.ForeignKey(Programs, verbose_name=u'Программа')
    caption = models.CharField(max_length=255, verbose_name=u'Заголовок передачи')
    date = models.DateField(u'Дата', default=dt.date.today())
    time_s = models.TimeField(u'Время начала', default=dt.datetime.now())
    time_e = models.TimeField(u'Время окончания', default=dt.datetime.now())
    description = RichTextField(u'Описание', blank=True)
    soundcloud = models.CharField(max_length=255, verbose_name=u'Код soundcloud', blank=True)

    def __unicode__(self):
        return u'%s [%s %s]' % (self.caption, self.date.strftime('%Y-%m-%d'), self.time_s.strftime('%H:%M:%S'))

    @models.permalink
    def get_absolute_url(self):
        s = self.__module__
        r = r'.(\w+).models$'
        app = re.findall(r, s)[0].lower()
        cls = self.__class__.__name__.lower()
        return ('%s_%s_archive' % (app, cls, ), [str(self.id)])

    def get_archive_date_for_datapicer(self):
        today = dt.date.today()
        alfa = self.date-today
        return '%dd' % alfa.days

    class Meta:
        ordering = ('-date', '-time_s', )
        verbose_name = u'Передача'
        verbose_name_plural = u'Архив программ'

class ProgramsArchivePhoto(PublishModel):
    program = models.ForeignKey(ProgramsArchive, verbose_name=u'Передача')
    photo = models.ImageField(verbose_name=u'Фотография', upload_to=u'upload', help_text=u'изображение обрезаеться до размеров 570x380')
    description = RichTextField(u'Описание', blank=True)
    weight = models.PositiveSmallIntegerField(u'Порядок', default=0)

    def __unicode__(self):
        return u'Фотография для %s' % (self.program)

    class Meta:
        ordering = ('weight', )
        verbose_name = u'Архивная фотография'
        verbose_name_plural = u'Архивные фотографии'


class Staff(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Имя')
    surname = models.CharField(max_length=255, verbose_name=u'Фамилия')
    name_t = models.CharField(max_length=255, verbose_name=u'Имя', help_text=u'творительный падеж')
    surname_t = models.CharField(max_length=255, verbose_name=u'Фамилия', help_text=u'творительный падеж')
    photo = models.ImageField(verbose_name=u'Фотография', upload_to=u'upload', null=True, blank=True, help_text=u'изображение обрезаеться до размеров 570x380')
    photo_min = models.ImageField(verbose_name=u'Фотография', upload_to=u'upload', null=True, blank=True, help_text=u'маленькая фотография, размером 207x138')
    text = RichTextField(u'Текст', blank=True)
    programs = models.ManyToManyField('Programs', through="ProxyMayakStaffPrograms", blank=True, related_name='programs', )
    weight = models.PositiveSmallIntegerField(u'Порядок', default=0)

    def __unicode__(self):
        return '%s %s' % (self.surname, self.name, )

    def name_surname(self):
        return '%s&nbsp;%s' % (self.name, self.surname, )

    def name_surname_t(self):
        return '%s&nbsp;%s' % (self.name_t, self.surname_t, )

    class Meta:
        verbose_name = u'Голос эфира'
        verbose_name_plural = u'Голоса эфира'
        ordering = ('weight', 'surname', 'name', )

    @models.permalink
    def get_absolute_url(self):
        s = self.__module__
        r = r'.(\w+).models$'
        app = re.findall(r, s)[0].lower()
        cls = self.__class__.__name__.lower()
        return ('%s_%s_communicate' % (app, cls, ), [self.name, self.surname, ])


class ProxyMayakStaffPrograms(models.Model):
    programs = models.ForeignKey(Programs)
    staff = models.ForeignKey(Staff)

    class Meta:
        db_table = 'Proxy_Mayak_Staff_Programs'
        auto_created = Programs


class Promo(PublishModel):
    title = models.CharField(u'название', max_length=200)
    url = models.CharField(u'ссылка', max_length=200, blank=True)
    program = models.ForeignKey(Programs, null=True, blank=True, help_text='При выборе программы ссылка на онную генерируется автоматически<br />и имеет приоритет перед заданной вручную ссылкой')
    photo = models.ImageField(u'изображение', upload_to='upload/promo', help_text=u'промо на главной размером 888x384')
    weight = models.SmallIntegerField(u'порядок', default=0)

    class Meta:
        ordering = ('weight', 'title', )
        verbose_name = u'промо'
        verbose_name_plural = u'промо'

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('mayak_index', [])


class Press(PublishModel):
    magazine = models.CharField(u'журнал', max_length=256)
    date = models.CharField(u'дата публикации', max_length=128)
    headline = models.CharField(u'название статьи', max_length=256)
    pdf = models.FileField(u'PDF', upload_to='upload/PDF')
    weight = models.SmallIntegerField(u'порядок', default=0)

    class Meta:
        ordering = ('weight', '-id', )
        verbose_name = u'пресса'
        verbose_name_plural = u'пресса'

    def __unicode__(self):
        return self.headline

yugregion/mayak_advertisers/views.py
# -*- coding: utf-8 -*-

from django.http import Http404
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext

from yugregion.mayak_advertisers.forms import ManagerConnectForm
from yugregion.mayak_advertisers.models import Managers, Action, Mayak_Research, Partners

def manager_list(request):
    manager_list = Managers.objects.all().order_by('weight')
    connect_form = ManagerConnectForm(request.GET or None)
    return render_to_response("advertisers/mayak_manager_list.html", RequestContext(request, {
        'manager_list': manager_list,
    	'connect_form': connect_form,
    }))

def action_list(request):
    action_list = Action.objects.published()
    return render_to_response("advertisers/mayak_action_list.html", RequestContext(request, {'action_list': action_list, }))

def action_detail(request, action_id=1):
    action = get_object_or_404(Action, id=action_id)
    return render_to_response("advertisers/mayak_action_detail.html", RequestContext(request, {'action': action, }))

def research(request):
    try:
        research = Mayak_Research.objects.published()[0]
    except IndexError:
        raise Http404
    return render_to_response("advertisers/mayak_research.html", RequestContext(request, {'research': research, }))

def manager_connect(request):
    connect_form = ManagerConnectForm(request.POST or None)
    if connect_form.is_valid():
        connect_form.save()
    context = RequestContext(request)
    context['connect_form'] = connect_form
    response = render_to_response('feedback/manager_connect_form.html', context)
    response.set_cookie('manager_connect_result', connect_form.is_valid())
    return response

def partners(request):
    partners_list = Partners.objects.published()
    return render_to_response("advertisers/mayak_partners_list.html", RequestContext(request, {
        'partners_list': partners_list,
    }))

#EOF

yugregion/mayak_consultation/views.py
# -*- coding: utf-8 -*-

from django.core.paginator import Paginator, EmptyPage
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse

from yugregion.mayak_consultation.models import Consiliario, Question,\
    SubjectConsultation
from yugregion.mayak_consultation.forms import AskConsultantForm,\
    BecomeConsultantForm


def _get_context_data(archive=False):
    context = dict()
    subject_list = Question.objects.published(
        consiliario__is_archive=archive
    ).exclude(answer='').values_list('consiliario__subject_id', flat=True).\
        distinct()
    context['subject_list'] = SubjectConsultation.objects.\
        filter(id__in=subject_list)

    context['consultant_list'] = Consiliario.objects.published(is_archive=archive)
    return context


def consultation(request, subject=None, archive=False):
    context = RequestContext(request, _get_context_data(archive))
    kwargs = dict({
        'consiliario__is_archive': archive,
    })
    if subject:
        kwargs.update(dict(consiliario__subject_id=subject))
        context['subject'] = get_object_or_404(SubjectConsultation,
            id=subject,
        )
    qs = Question.objects.published(**kwargs).exclude(answer='')

    paginator = Paginator(qs, 10, 3, True)
    page = request.GET.get('page', 1)
    try:
        question_list = paginator.page(page)
    except EmptyPage:
        question_list = paginator.page(paginator.num_pages)

    context['archive'] = archive
    context['question_list'] = question_list
    template = 'consultation/mayak_consultation.html'
    return render_to_response(template, context)


def consultant(request, id, archive=False):
    consult = get_object_or_404(Consiliario, id=id, is_published=True)
    context = RequestContext(request, _get_context_data(archive))

    page = request.GET.get('page', 1)
    qs = Question.objects.published(consiliario=consult).exclude(answer='')
    paginator = Paginator(qs, 10, 3, True)
    try:
        question_list = paginator.page(page)
    except EmptyPage:
        question_list = paginator.page(paginator.num_pages)

    context['archive'] = archive
    context['consult'] = consult
    context['question_list'] = question_list
    template = 'consultation/mayak_consultant.html'
    return render_to_response(template, context)


def consultant_ask(request, id):
    consult = get_object_or_404(Consiliario, id=id, is_archive=False,
                                is_published=True)

    form = AskConsultantForm(request.POST or None)
    if form.is_valid():
        form.save(consultant=consult)
        return HttpResponseRedirect(reverse('mayak_consultant_ask_done', args=[consult.id]))

    context = RequestContext(request, _get_context_data())

    context['consult'] = consult
    context['form'] = form
    template = 'consultation/mayak_consultant_form.html'
    return render_to_response(template, context)


def consultant_ask_done(request, id):
    context = RequestContext(request, _get_context_data())
    context['consult'] = get_object_or_404(Consiliario, id=id, is_archive=False,
                                           is_published=True)

    template = 'consultation/mayak_consultant_done.html'
    return render_to_response(template, context)


def consultant_become(request):
    form = BecomeConsultantForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('mayak_consultant_become_done'))

    context = RequestContext(request, _get_context_data())

    context['form'] = form
    template = 'consultation/mayak_become_consultant_form.html'
    return render_to_response(template, context)


def consultant_become_done(request):
    context = RequestContext(request, _get_context_data())

    template = 'consultation/mayak_become_consultant_done.html'
    return render_to_response(template, context)


def archive(request):
    context = RequestContext(request, _get_context_data(True))

    subject_list = Question.objects.published(
        consiliario__is_archive=True
    ).exclude(answer='').values_list('consiliario__subject_id', flat=True).\
        distinct()
    context['subject_list'] = SubjectConsultation.objects.\
        filter(id__in=subject_list)

    context['archive'] = True
    template = 'consultation/mayak_consultant_archive.html'
    return render_to_response(template, context)

yugregion/templates/program/mayak_program_archive.html
{% extends "mayak_layout.html" %}

{% load static from staticfiles %}
{% load thumbnails %}


{% block preheadjs %}
	<link rel="stylesheet" href="{% static 'css/jquery.datapiker.css' %}">
{% endblock %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script src="{% static 'js/jquery-ui.js' %}"></script>
	<script type="text/javascript" >
		$(function() {
			$('.scroll-pane').jScrollPane({ horizontalDragMinWidth: 20 });
		});

		$.datepicker.regional['ru'] = {
			closeText: 'Закрыть',
			prevText: '&#x3c;Пред',
			nextText: 'След&#x3e;',
			currentText: 'Сегодня',
			monthNames: ['Январь','Февраль','Март','Апрель','Май','Июнь', 'Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
			monthNamesShort: ['Янв','Фев','Мар','Апр','Май','Июн', 'Июл','Авг','Сен','Окт','Ноя','Дек'],
			dayNames: ['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'],
			dayNamesShort: ['вск','пнд','втр','срд','чтв','птн','сбт'],
			dayNamesMin: ['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],
			weekHeader: 'Не',
			dateFormat: 'dd.mm.yy',
			firstDay: 1,
			isRTL: false,
			showMonthAfterYear: false,
			yearSuffix: ''
		};
		$.datepicker.setDefaults($.datepicker.regional['ru']);

		var links = { {% for archive_programm in transfer.program.programsarchive_set.published %}{% if not forloop.first %},{% endif %}"{{ archive_programm.date|date:'d.m.Y' }}": {"url":'{{ archive_programm.get_absolute_url }}',"text":'{{ archive_programm.caption|safe }}'}{% endfor %} };

		function available(date) {
			var values = [ date.getDate(), date.getMonth()+1 ];
			for ( var id in values ) {values[ id ] = values[ id ].toString().replace( /^([0-9])$/, '0$1' );}
			dmy = values[ 0 ]+'.'+values[ 1 ]+'.'+date.getFullYear()
			if ( links[dmy] && setDate == values[ 1 ]+'.'+date.getFullYear() ){
				$('#archive_list').append('<p>'+dmy+'<br />'+links[dmy]["text"]+'<br /><a href="'+links[dmy]["url"]+'" >Послушать запись</a></p>');
				return [true, "Available","Available"];
			} else {
				return [false,"unAvailable","unAvailable"];
			}
		}

		function show_archive(date) {
			if ( links[date] ) {
				document.location.href = links[date]['url'];
			}
			return false
		}

		function clear_archive(year, month) {
			setDate = month.toString().replace( /^([0-9])$/, '0$1' )+'.'+year;
			$('#archive_list').text('')
		}

		var setDate = "{{ transfer.date|date:'m.Y' }}";

		$(function() {
			$( "#datepicker" ).datepicker({
				changeYear: true,
				minDate: "{{ transfer.program.get_earliest_archive_date_for_datapicer }}",
				maxDate: "{{ transfer.program.get_latest_archive_date_for_datapicer }}",
				defaultDate: "{{ transfer.get_archive_date_for_datapicer }}",
				beforeShowDay: available,
				onChangeMonthYear: clear_archive,
				onSelect: show_archive
			});
		});
	</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="program-frame">
			<div class="block_breadcrumbs" >
				{% for crumb in breadcrumbs %}
					<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">
						{{ crumb|safe }}
					</a>
					{% if not forloop.last %}
					&nbsp;&rarr;&nbsp;
					{% endif %}
				{% endfor %}
				&nbsp;&rarr;&nbsp;
				<a href="{{ transfer.program.get_absolute_url }}" class="breadcrumbs" >{{ transfer.program.title|safe }}</a>
				&nbsp;&rarr;&nbsp;{{ transfer.date }}</div>
			<h3>{{ transfer.program.title|safe }}</h3>
			<h4>{{ transfer.caption|safe }}</h4>
			<p>{{ transfer.date }}</p>
			{% for photo in transfer.programsarchivephoto_set.all %}
				{% if forloop.first %}
					<ul class="img-list item-photo-group">
				{% endif %}
					<li class="item-photo-hldr">
						<a href="{{ photo.photo.path|thumbnail:"570x380,crop" }}" class="photo">
							<img src="{{ photo.photo.path|thumbnail:"281x203,crop" }}" width="281" height="203" alt="{{ photo.photo.description|safe }}" />
							<span class="shadow"></span>
						</a>
					</li>
				{% if forloop.last %}
					</ul>
				{% endif %}
			{% endfor %}
			<div class="description">{{ transfer.description|safe }}</div>
			{{ transfer.soundcloud|safe }}

			<div class="archive" >
				<div class="title">Архив программы</div>
				<hr calss="hr_datepicker" />
				<div id="datepicker" ></div>
				<div id="archive_list" ></div>
			</div>

			<div class="content">
				<div id="mc-container"></div>
				<script type="text/javascript">
					var mcSite = '36065';
					(function() {
						var mc = document.createElement('script');
						mc.type = 'text/javascript';
						mc.async = true;
						mc.src = '//cackle.me/mc.widget-min.js';
						(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(mc);
					})();
				</script>
				<a href="http://cackle.me" id="mc-link">система комментирования <b style="color:#4FA3DA">CACKL</b><b style="color:#F65077">E</b></a>
			</div>
		</div>
	</div><!--main-frame end-->

{% endblock %}

{% block popup %}
	<div class="popup-holder" style="left:-0px; display: none;">
		<div class="bg">&nbsp;</div>
		<div class="popup image">
			<a href="#" class="close"></a>
			<a href="#" class="next"></a>
			<a href="#" class="prev"></a>
			<img src="" width="570" height="380" alt="" />
		</div>
	</div>
{% endblock %}

yugregion/templates/program/mayak_video_archive.html
{% extends "mayak_layout.html" %}

{% load static from staticfiles %}
{% load thumbnails %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script type="text/javascript">
		$(function(){$('.scroll-pane').jScrollPane({
			horizontalDragMinWidth: 20
		});});
	</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="program-frame">
			<div class="block_breadcrumbs" >{% for crumb in breadcrumbs %}<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">{{ crumb|safe }}</a>{% if not forloop.last %}&nbsp;&rarr;&nbsp;{% endif %}{% endfor %}&nbsp;&rarr;&nbsp;{{ transfer.program.title|safe }}&nbsp;{{ transfer.date }}</div>
			<h3>{{ transfer.program.title|safe }}</h3>
			<h4>{{ transfer.title|safe }}</h4>
			<p>{{ transfer.date }}</p>
{% comment %}
			{% for photo in transfer.programsarchivephoto_set.all %}
				{% if forloop.first %}
					<ul class="img-list item-photo-group">
				{% endif %}
					<li class="item-photo-hldr">
						<a href="{{ photo.photo.path|thumbnail:"570x380,crop" }}" class="photo">
							<img src="{{ photo.photo.path|thumbnail:"281x203,crop" }}" width="281" height="203" alt="{{ photo.photo.description|safe }}" />
							<span class="shadow"></span>
						</a>
					</li>
				{% if forloop.last %}
					</ul>
				{% endif %}
			{% endfor %}
{% endcomment %}
			{{ transfer.video|safe }}
			<div class="description">{{ transfer.text|safe }}</div>
			<div class="content">
				<div id="mc-container"></div>
				<script type="text/javascript">
					var mcSite = '36065';
					(function() {
					    var mc = document.createElement('script');
					    mc.type = 'text/javascript';
					    mc.async = true;
					    mc.src = '//cackle.me/mc.widget-min.js';
					    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(mc);
					})();
				</script>
				<a href="http://cackle.me" id="mc-link">система комментирования <b style="color:#4FA3DA">CACKL</b><b style="color:#F65077">E</b></a>
			</div>
		</div>
	</div><!--main-frame end-->

{% endblock %}

{% block popup %}
	<div class="popup-holder" style="left:-0px; display: none;">
		<div class="bg">&nbsp;</div>
		<div class="popup image">
			<a href="#" class="close"></a>
			<a href="#" class="next"></a>
			<a href="#" class="prev"></a>
			<img src="" width="570" height="380" alt="" />
		</div>
	</div>
{% endblock %}