yugregion/mayak_news/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import Rss


urlpatterns = patterns('yugregion.mayak_news.views',
    url(r'^$', 'news_index', name='mayak_news_list'),
    url(r'^page_(?P<page>\d+)/$', 'news_index', name='mayak_news_list_page'),
    url(r'^date_(?P<date>[0-9]{4}/[0-9]{2}/[0-9]{2})/$', 'news_date', name='mayak_news_date_list'),
    url(r'^date/json/$', 'news_date_json', name='mayak_news_date_json'),
    url(r'^(?P<news_id>\d+)/$', 'news_show', name='mayak_news_show'),
    url(r'^(?P<news_id>\d+)/more/$', 'day_news_more', name='mayak_day_news_more'),
    url(r'^rss/$', Rss()),
)

yugregion/mayak_video/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('yugregion.mayak_video.views',
    url(r'^$', 'program_video_archive', name='mayak_nucleum_program_video_archive_archive_last'),
    url(r'^(?P<pk>\d+)$', 'program_video_archive', name='mayak_nucleum_program_video_archive_archive'),
    url(r'^last/$', 'program_video_archive', name='mayak_nucleum_program_video_archive_archive_last'),
)

yugregion/shanson_news/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('yugregion.shanson_news.views',
    url(r'^$', 'news_index', name='shanson_news_list'),
    url(r'^page_(?P<page>\d+)/$', 'news_index', name='shanson_news_list_page'),
    url(r'^(?P<news_id>\d+)/$', 'news_show', name='shanson_news_show'),
    url(r'^(?P<news_id>\d+)/more/$', 'day_news_more', name='shanson_day_news_more'),
)

yugregion/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from planb.core.urls import urlpatterns

local_urlpatterns = patterns('',
    url(r'^mayak/', include('yugregion.mayak_nucleum.urls')),
    url(r'^shanson/', include('yugregion.shanson_nucleum.urls')),
)

urlpatterns = local_urlpatterns + urlpatterns

planb/gallery/models.py
# -*- coding: utf-8 -*-

import datetime as dt

from django.db import models

from ckeditor.fields import RichTextField

from planb.core.models import PublishModel


class Gallery(models.Model):
    title = models.CharField(max_length=255, verbose_name=u'Заголовок')
    description = RichTextField(verbose_name=u'Описание', blank=True)
    weight = models.PositiveSmallIntegerField(u'Порядок',  default=0)

    def __unicode__(self):
        return u'%s' % (self.title, )

    class Meta:
        ordering = ('weight', '-id', )
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галереи'

class Gallery_Img(PublishModel):
    gallery = models.ForeignKey(Gallery)
    img = models.FileField(verbose_name=u'Фотография', upload_to='upload/Gallery_Img')
    description = RichTextField(verbose_name=u'Описание', blank=True)
    weight = models.PositiveSmallIntegerField(u'Порядок',  default=0)

    def __unicode__(self):
        return u'%s - %s [%s]' % (self.gallery, self.description[:60], self.is_published)

    class Meta:
        ordering = ('weight', 'id', )
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'

#EOF

yugregion/mayak_advertisers/views.py
# -*- coding: utf-8 -*-

from django.http import Http404
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext

from yugregion.mayak_advertisers.forms import ManagerConnectForm
from yugregion.mayak_advertisers.models import Managers, Action, Mayak_Research, Partners

def manager_list(request):
    manager_list = Managers.objects.all().order_by('weight')
    connect_form = ManagerConnectForm(request.GET or None)
    return render_to_response("advertisers/mayak_manager_list.html", RequestContext(request, {
        'manager_list': manager_list,
    	'connect_form': connect_form,
    }))

def action_list(request):
    action_list = Action.objects.published()
    return render_to_response("advertisers/mayak_action_list.html", RequestContext(request, {'action_list': action_list, }))

def action_detail(request, action_id=1):
    action = get_object_or_404(Action, id=action_id)
    return render_to_response("advertisers/mayak_action_detail.html", RequestContext(request, {'action': action, }))

def research(request):
    try:
        research = Mayak_Research.objects.published()[0]
    except IndexError:
        raise Http404
    return render_to_response("advertisers/mayak_research.html", RequestContext(request, {'research': research, }))

def manager_connect(request):
    connect_form = ManagerConnectForm(request.POST or None)
    if connect_form.is_valid():
        connect_form.save()
    context = RequestContext(request)
    context['connect_form'] = connect_form
    response = render_to_response('feedback/manager_connect_form.html', context)
    response.set_cookie('manager_connect_result', connect_form.is_valid())
    return response

def partners(request):
    partners_list = Partners.objects.published()
    return render_to_response("advertisers/mayak_partners_list.html", RequestContext(request, {
        'partners_list': partners_list,
    }))

#EOF

yugregion/mayak_consultation/views.py
# -*- coding: utf-8 -*-

from django.core.paginator import Paginator, EmptyPage
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse

from yugregion.mayak_consultation.models import Consiliario, Question,\
    SubjectConsultation
from yugregion.mayak_consultation.forms import AskConsultantForm,\
    BecomeConsultantForm


def _get_context_data(archive=False):
    context = dict()
    subject_list = Question.objects.published(
        consiliario__is_archive=archive
    ).exclude(answer='').values_list('consiliario__subject_id', flat=True).\
        distinct()
    context['subject_list'] = SubjectConsultation.objects.\
        filter(id__in=subject_list)

    context['consultant_list'] = Consiliario.objects.published(is_archive=archive)
    return context


def consultation(request, subject=None, archive=False):
    context = RequestContext(request, _get_context_data(archive))
    kwargs = dict({
        'consiliario__is_archive': archive,
    })
    if subject:
        kwargs.update(dict(consiliario__subject_id=subject))
        context['subject'] = get_object_or_404(SubjectConsultation,
            id=subject,
        )
    qs = Question.objects.published(**kwargs).exclude(answer='')

    paginator = Paginator(qs, 10, 3, True)
    page = request.GET.get('page', 1)
    try:
        question_list = paginator.page(page)
    except EmptyPage:
        question_list = paginator.page(paginator.num_pages)

    context['archive'] = archive
    context['question_list'] = question_list
    template = 'consultation/mayak_consultation.html'
    return render_to_response(template, context)


def consultant(request, id, archive=False):
    consult = get_object_or_404(Consiliario, id=id, is_published=True)
    context = RequestContext(request, _get_context_data(archive))

    page = request.GET.get('page', 1)
    qs = Question.objects.published(consiliario=consult).exclude(answer='')
    paginator = Paginator(qs, 10, 3, True)
    try:
        question_list = paginator.page(page)
    except EmptyPage:
        question_list = paginator.page(paginator.num_pages)

    context['archive'] = archive
    context['consult'] = consult
    context['question_list'] = question_list
    template = 'consultation/mayak_consultant.html'
    return render_to_response(template, context)


def consultant_ask(request, id):
    consult = get_object_or_404(Consiliario, id=id, is_archive=False,
                                is_published=True)

    form = AskConsultantForm(request.POST or None)
    if form.is_valid():
        form.save(consultant=consult)
        return HttpResponseRedirect(reverse('mayak_consultant_ask_done', args=[consult.id]))

    context = RequestContext(request, _get_context_data())

    context['consult'] = consult
    context['form'] = form
    template = 'consultation/mayak_consultant_form.html'
    return render_to_response(template, context)


def consultant_ask_done(request, id):
    context = RequestContext(request, _get_context_data())
    context['consult'] = get_object_or_404(Consiliario, id=id, is_archive=False,
                                           is_published=True)

    template = 'consultation/mayak_consultant_done.html'
    return render_to_response(template, context)


def consultant_become(request):
    form = BecomeConsultantForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('mayak_consultant_become_done'))

    context = RequestContext(request, _get_context_data())

    context['form'] = form
    template = 'consultation/mayak_become_consultant_form.html'
    return render_to_response(template, context)


def consultant_become_done(request):
    context = RequestContext(request, _get_context_data())

    template = 'consultation/mayak_become_consultant_done.html'
    return render_to_response(template, context)


def archive(request):
    context = RequestContext(request, _get_context_data(True))

    subject_list = Question.objects.published(
        consiliario__is_archive=True
    ).exclude(answer='').values_list('consiliario__subject_id', flat=True).\
        distinct()
    context['subject_list'] = SubjectConsultation.objects.\
        filter(id__in=subject_list)

    context['archive'] = True
    template = 'consultation/mayak_consultant_archive.html'
    return render_to_response(template, context)

yugregion/mayak_news/views.py
# -*- coding: utf-8 -*-

import datetime as dt
import json

from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.syndication.views import Feed

from yugregion.mayak_news.models import News
from yugregion.mayak_news.utils import add_months


_paginate_per_page = 25

class Rss(Feed):
    title = "Радио «Маяк Ростов». Новости"
    link = "/mayak/news/"
    description = "Свежие новости Ростова и области."

    def items(self):
        return News.objects.published(date__lte=dt.date.today()).\
        exclude(date=dt.date.today(), time__gte=dt.datetime.now().time())[:50]
    
    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.text
    
def news_index(request, page=1):
    qs = News.objects.published(date__lte=dt.date.today()).\
        exclude(date=dt.date.today(), time__gte=dt.datetime.now().time())
    paginator = Paginator(qs, _paginate_per_page, 3, True)
    try:
        news_list = paginator.page(page)
    except EmptyPage:
        news_list = paginator.page(paginator.num_pages)

    s = news_list[-1].date
    e = news_list[0].date

    news_day_list = qs.filter(
        date__lte=add_months(e, 2),
        date__gte=add_months(s, -1)).dates('date', 'day')

    today = dt.date.today()

    earliest_date = qs.order_by('date')[0].date
    minDate = '%dd' % (earliest_date-today).days

    latest_date = qs.latest('date').date
    maxDate = '%dd' % (latest_date-today).days

    defaultDate = '%dd' % (e-today).days

    return render_to_response("news/mayak_news_list.html", RequestContext(request, {
        'news_list': news_list,
        'news_day_list': news_day_list,
        'minDate': minDate,
        'maxDate': maxDate,
        'defaultDate': defaultDate,
    }))

def news_date(request, date):
    date = dt.datetime.strptime(date, '%Y/%m/%d')
    today = dt.date.today()
    now = dt.datetime.now().time()
    alfa = News.objects.published(date__gt=date).exclude(
        date=today,
        time__gte=now
    ).count()
    page = alfa / _paginate_per_page + 1
    return HttpResponseRedirect(reverse('mayak_news_list_page',
                                kwargs=dict(page=page)))

def news_show(request, news_id):
    today = dt.date.today()
    now = dt.datetime.now().time()
    try:
        news = News.objects.published(id=news_id, date__lte=today).\
            exclude(date=today, time__gte=now)[0]
    except IndexError:
        raise Http404
    day_news_list = News.objects.published(date=news.date).exclude(
        date=today,
        time__gte=now
    ).exclude(id=news.id).order_by('?')[:3]
    return render_to_response("news/mayak_news_show.html", RequestContext(request, {
        'news': news,
        'day_news_list': day_news_list,
    }))


def day_news_more(request, news_id):
    today = dt.date.today()
    now = dt.datetime.now().time()
    try:
        news = News.objects.published(id=news_id, date__lte=today).\
            exclude(date=today, time__gte=now)[0]
    except IndexError:
        raise Http404
    alfa = News.objects.published(date__gt=news.date).exclude(
        date=today,
        time__gte=now
    ).count()
    page = alfa / _paginate_per_page + 1
    return HttpResponseRedirect(reverse('mayak_news_list_page',
                                kwargs=dict(page=page)))


def news_date_json(request):
    if request.method == 'POST':
        date = dt.datetime.strptime(request.POST.get('date'), '%m.%Y')
        date_s = add_months(date, -1)
        date_e = add_months(date, 2)
        qs = News.objects.published(date__lte=date_e, date__gte=date_s).\
            exclude(date=dt.date.today(), time__gte=dt.datetime.now().time()).\
            dates('date', 'day')
        news_day_list = dict()
        for i in qs:
            news_day_list.update({i.strftime('%d.%m.%Y'):{"url":\
            reverse('mayak_news_date_list', args=[i.strftime('%Y/%m/%d')])}})

        return HttpResponse(json.dumps(news_day_list),
            content_type="application/json")
    return Http404()

yugregion/mayak_nucleum/views.py
# -*- coding: utf-8 -*-

import datetime as dt

from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response,\
    get_list_or_404, redirect
from django.template import RequestContext
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from yugregion.mayak_news.models import News
from yugregion.mayak_nucleum.models import Hospes, Programs, Promo,\
    ProgramsArchive, Staff, Press
from yugregion.mayak_nucleum import forms


def index(request):
    hospes_list = Hospes.objects.published()
    news_last = News.objects.published(date__lte=dt.date.today()).\
        exclude(date=dt.date.today(), time__gte=dt.datetime.now().time())[:10]
    promo_list = Promo.objects.published()
    return render_to_response("nucleum/mayak_index.html", RequestContext(request, {
        'news_last': news_last,
        'hospes_list': hospes_list,
        'promo_list': promo_list,
    }))

def program_list(request):
    program_list = Programs.objects.filter(is_published=True).\
        order_by('-display', 'weight')
    return render_to_response("program/mayak_program_list.html", RequestContext(request, {
        'program_list': program_list,
    }))

def program_detail(request, prog_id=1):
    program = get_object_or_404(Programs, id=prog_id)
    return render_to_response("program/mayak_program_detail.html", RequestContext(request, {
        'program': program,
    }))

def program_archive(request, trans_id='Alai Oli'):
    if trans_id != 'Alai Oli':
        transfer = get_object_or_404(ProgramsArchive, id=trans_id)
    elif ProgramsArchive.objects.count():
        transfer = ProgramsArchive.objects.published()[0]
    else:
        raise Http404
    return render_to_response("program/mayak_program_archive.html", RequestContext(request, {
        'transfer': transfer,
    }))

def about_index(request):
    voices_list = Staff.objects.all()
    press_list = Press.objects.published()
    return render_to_response("nucleum/mayak_about.html", RequestContext(request, {
        'voices_list': voices_list,
        'press_list': press_list,
    }))

def voices_communicate(request, name, surname, id=0):
    voice = get_object_or_404(Staff, name=name, surname=surname)
    voice_list = Staff.objects.exclude(name=name, surname=surname)
    return render_to_response("nucleum/mayak_communicate.html", RequestContext(request, {
        'voice': voice,
        'voice_list': voice_list,
    }))


def voices_communicate(request, name, surname, id=0):
    voice = get_object_or_404(Staff, name=name, surname=surname)
    voice_list = Staff.objects.exclude(name=name, surname=surname)
    return render_to_response("nucleum/mayak_communicate.html", RequestContext(request, {
        'voice': voice,
        'voice_list': voice_list,
    }))


class RadioanchormanForm(FormView):
    template_name = 'nucleum/mayak_radioanchorman.html'
    form_class = forms.RadioanchormanForm
    success_url = 'done/'

    def form_valid(self, form):
        form.save(self.request.FILES['face'])
        return super(RadioanchormanForm, self).form_valid(form)


class RememberAndProud(FormView):
    template_name = 'nucleum/mayak_rememberandproud.html'
    form_class = forms.RememberAndProudForm
    success_url = 'done/'
    
    def get_context_data(self, **kwargs):
        context = super(RememberAndProud, self).get_context_data(**kwargs)
        context['audio_archive'] = Programs.objects.get(id=14).programsarchive_set.published()
        #14
        return context
    
    def form_valid(self, form):
        form.save()
        return super(RememberAndProud, self).form_valid(form)

class RadioanchormanDoneTemplate(TemplateView):
    template_name = 'nucleum/mayak_radioanchorman_done.html'

class RememberAndProudDoneTemplate(TemplateView):
    template_name = 'nucleum/mayak_rememberandproud_done.html'

yugregion/templates/pages/mayak_contacts.html
{% extends "mayak_layout.html" %}

{% load static from staticfiles %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/clear-form-fields.js' %}"></script>
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true&language=ru"></script>
	<script type="text/javascript">
		$(function(){$('.scroll-pane').jScrollPane({
			horizontalDragMinWidth: 20
		});});
	</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="program-frame">
			<div class="block_breadcrumbs" >{% for crumb in breadcrumbs %}<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">{{ crumb|safe }}</a>{% if not forloop.last %}&nbsp;&rarr;&nbsp;{% endif %}{% endfor %}&nbsp;&rarr;&nbsp;{{ current_node.title|safe }}</div>
			<h2>{{ current_root_node|safe }}</h2>
			<div class="map-box">
				<div id="map_canvas" style="width: 867px; height: 383px;"></div>
			</div>
			{{ current_node.content|safe }}
		</div>
	</div>
{% endblock %}

{% block jsfoot %}
	<script type="text/javascript">
		var mapOptions = {
		  center: new google.maps.LatLng(47.226621, 39.730189),
		  zoom: 18,
		  mapTypeId: google.maps.MapTypeId.ROADMAP
		};
		var map = new google.maps.Map(document.getElementById("map_canvas"),
			mapOptions);
		var marker = new google.maps.Marker({
			position: new google.maps.LatLng(47.226621, 39.730189),
			map: map,
			title:"Радио «Маяк Ростов»",
			draggable: false,
			animation: google.maps.Animation.DROP,
		});
	</script>
{% endblock %}

yugregion/templates/pages/mayak_default.html
{% extends "mayak_layout.html" %}

{% load static from staticfiles %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/clear-form-fields.js' %}"></script>
	<script type="text/javascript">
		$(function(){$('.scroll-pane').jScrollPane({
			horizontalDragMinWidth: 20
		});});
	</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="program-frame">
			<div class="block_breadcrumbs" >{% for crumb in breadcrumbs %}<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">{{ crumb|safe }}</a>{% if not forloop.last %}&nbsp;&rarr;&nbsp;{% endif %}{% endfor %}&nbsp;&rarr;&nbsp;{{ current_node.title|safe }}</div>
			<h2>{{ current_root_node|safe }}</h2>
			{{ current_node.content|safe }}
	</div>
{% endblock %}

yugregion/templates/pages/mayak_default_submenu.html
{% extends "mayak_layout.html" %}

{% load static from staticfiles %}
{% load thumbnails %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script type="text/javascript">
		$(function(){$('.scroll-pane').jScrollPane({
			horizontalDragMinWidth: 20
		});});
	</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="program-frame">
			<div class="block_breadcrumbs" >{% for crumb in breadcrumbs %}<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">{{ crumb|safe }}</a>{% if not forloop.last %}&nbsp;&rarr;&nbsp;{% endif %}{% endfor %}&nbsp;&rarr;&nbsp;{{ current_node.title|safe }}</div>
			<h2>{{ current_root_node.title|safe }}</h2>
			<div class="content-holder">

				{% include "includes/submenu.html" %}

				<div class="content">
					{{ current_node.content|safe }}
					{% if current_node.gallery %}
						<div class="article">
							<ul class="img-list item-photo-group">
								{% for img in current_node.gallery.gallery_img_set.all %}
									<li class="item-photo-hldr">
										<a href="{{ img.img.path|thumbnail:"570x380,crop" }}" class="photo"><img src="{{ img.img.path|thumbnail:"105x71,crop" }}" width="105" height="71" alt="{% if img.description != '' %}{{ img.description|slice:"0:70" }}{% endif %}" /><span class="shadow"></span></a>
									</li>
								{% endfor %}
							</ul>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div><!--main-frame end-->
{% endblock %}

{% block popup %}
	<div class="popup-holder" style="left:-0px; display: none;">
		<div class="bg">&nbsp;</div>
		<div class="popup image">
			<a href="#" class="close"></a>
			<a href="#" class="next"></a>
			<a href="#" class="prev"></a>
			<img src="" width="570" height="380" alt="" />
		</div>
	</div>
{% endblock %}

yugregion/templates/pages/mayak_default_two_coll.html
{% extends "mayak_layout.html" %}

{% load static from staticfiles %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script type="text/javascript">
		$(window).load(function(){$('.scroll-pane').jScrollPane({
			verticalDragMinHeight: 20,
			verticalDragMaxHeight: 120,
			horizontalDragMinWidth: 20,
			horizontalDragMaxWidth: 120
		});});
	</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="content-holder">
			<div class="block_breadcrumbs" >{% for crumb in breadcrumbs %}<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">{{ crumb|safe }}</a>{% if not forloop.last %}&nbsp;&rarr;&nbsp;{% endif %}{% endfor %}&nbsp;&rarr;&nbsp;{{ current_node.title|safe }}</div>
			<div class="content">
				<div class="article-box">
					<h2>{{ current_root_node|safe }}</h2>
					{{ current_node.content|safe }}
				</div>
			</div>
			<div class="aside no-title">
				<div class="aside-box" style="height:292px;">
				</div>
			</div>
		</div><!--content-holder end-->
	</div>
{% endblock %}

yugregion/templates/pages/shanson_default_submenu.html
{% extends "shanson_layout.html" %}

{% load static from staticfiles %}
{% load thumbnails %}

{% block headjs %}
	<script type="text/javascript" src="{% static 'js/jquery.jscrollpane.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.mousewheel.js' %}"></script>
	<script type="text/javascript">$(function(){$('.scroll-pane').jScrollPane({horizontalDragMinWidth: 20});});</script>
{% endblock %}

{% block body %}
	<div class="main-frame">
		<div class="program-frame">
			<div class="block_breadcrumbs" >{% for crumb in breadcrumbs %}<a class="breadcrumbs" href="{{ crumb.get_absolute_url }}">{{ crumb|safe }}</a>{% if not forloop.last %}&nbsp;&rarr;&nbsp;{% endif %}{% endfor %}&nbsp;&rarr;&nbsp;{{ current_node.title|safe }}</div>
			<h2>{{ current_root_node.title|safe }}</h2>
			<div class="content-holder">

				{% include "includes/submenu.html" %}

				<div class="content">
					<div class="article">
						{{ current_node.content|safe }}

						{% if current_node.gallery %}
							<ul class="img-list item-photo-group">
								{% for img in current_node.gallery.gallery_img_set.all %}
									<li class="item-photo-hldr">
										<a href="{{ img.img.path|thumbnail:"570x380,crop" }}" class="photo"><img src="{{ img.img.path|thumbnail:"105x71,crop" }}" width="105" height="71" alt="{% if img.description != '' %}{{ img.description|slice:"0:70" }}{% endif %}" /><span class="shadow"></span></a>
									</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div><!--main-frame end-->
{% endblock %}

{% block popup %}
	<div class="popup-holder" style="left:-0px; display: none;">
		<div class="bg">&nbsp;</div>
		<div class="popup image">
			<a href="#" class="close"></a>
			<a href="#" class="next"></a>
			<a href="#" class="prev"></a>
			<img src="" width="570" height="380" alt="" />
		</div>
	</div>
{% endblock %}